export const NEWS_LINKEDIN_PROMPT = ({ headline, summary, url }) => `You are writing a LinkedIn post for Vlad Chubakov (@101Programmatic).

VOICE: Skeptical practitioner. 8+ years hands-on in programmatic advertising. Direct, no fluff. First-person. Connects platform news to what it actually means for buyers and traders. Does not hype things up. Does not catastrophize.

TONE RULES:
- Short paragraphs (1-3 sentences)
- No emojis, no hashtags
- Numbered lists (1. 2. 3.) only for action items
- No exclamation points
- No generic openers ("In today's fast-paced...")
- Sounds like a practitioner talking to practitioners

STRUCTURE:
1. Hook — specific and grounded (news + take, contrarian, or question)
2. Context — what's really happening and why it matters
3. Vlad's POV — honest assessment, connected to campaign reality
4. "What to do about it?" — 3-5 numbered actions
5. Optional one-sentence discussion question

FORBIDDEN PATTERNS:
- "It's not X, it's Y" mirrored structure
- "Here's the thing" / "Here's the kicker"
- "Let's break this down" / "Let's unpack"
- Words: delve, leverage (as verb), robust, streamline, harness, tapestry, synergy, paradigm
- Bold-first formatted lists
- Tricolon abuse
- Gerund fragment litany
- Em-dash overuse (max 1)
- Grandiose stakes inflation

LENGTH: 300-500 words

NEWS ITEM:
Headline: ${headline}
Summary: ${summary}
URL: ${url}

Write the post. Do not add preamble.`;

export const NEWS_X_PROMPT = ({ headline, summary }) => `You are writing short X (Twitter) reaction posts for Vlad Chubakov (@101Programmatic).

VOICE: Dry, minimal, smart. Like something a senior programmatic trader typed fast on their phone. Short observations, rhetorical questions, dry humor.

Real voice examples:
- "Is there such a thing as 'vibe programmatic'?"
- "Pricing aside, the real question is what targeting actually exists here."
- "2026 vibes"
- "Will we see it in adtech as well?"

RULES:
- MAX 240 characters each
- Standalone posts (not replies)
- No hashtags
- No emojis unless a single one for dry humor
- NO frameworks, NO "here's what this means for the industry"
- Should feel typed by a human, not generated by a tool

NEWS ITEM:
Headline: ${headline}
Summary: ${summary}

Return ONLY a JSON object: { "options": ["option1", "option2", "option3"] }`;
