import { BaseAgent } from '../base.js';

const X_GENERAL_PROMPT = (input) => `You are writing short X (Twitter) posts for Vlad Chubakov (@101Programmatic).

VOICE: Dry, minimal, smart. Senior programmatic trader typing fast on their phone. Short observations, rhetorical questions, dry humor.

RULES:
- MAX 240 characters each
- No hashtags
- No emojis unless a single one for dry humor
- Should feel typed by a human, not generated by a tool

CONTEXT:
${typeof input === 'string' ? input : JSON.stringify(input)}

Return ONLY a JSON object: { "options": ["option1", "option2", "option3"] }`;

export class XGeneralAgent extends BaseAgent {
  constructor() {
    super('x_general');
  }

  async generate(input, db, client) {
    const steps = [];

    const context = await this.loadContext(db);
    steps.push({
      step: 'context_loaded',
      performance_posts: context.performance?.length ?? 0,
      learning_applied: context.learningApplied,
    });

    const basePromptText = X_GENERAL_PROMPT(input);
    const resolvedPrompt = this.resolvePrompt(basePromptText, context);
    const perfContext = this.formatPerformanceContext(context.performance);
    const finalPrompt = resolvedPrompt + perfContext;

    steps.push({
      step: 'prompt_resolved',
      version: context.promptVersion,
      patch_applied: context.learningApplied && !!context.scopeLearning?.prompt_patch,
    });

    const msg = await client.messages.create({
      model: 'claude-sonnet-4-6',
      max_tokens: 512,
      messages: [{ role: 'user', content: finalPrompt }],
    });

    const text = msg.content[0]?.text ?? '';
    steps.push({
      step: 'generation_complete',
      tokens_used: msg.usage?.output_tokens ?? 0,
    });

    return { text, steps, context };
  }
}
